### ISSUE TITLE
Problem with launching your project

### ISSUE THREAD

**Issue by ghost** [LeoRover/leo_simulator#3]
Siema guys, 

i've cloned and set up your project put if i start your project via "roslaunch leo_gazebo leo_gazebo.launch" i get this error:

"Resource not found: The following package was not found in <arg default="$(find leo_description)/urdf/leo_sim.urdf.xacro" name="model"/>: leo_description"

For me it seems like there misses something, do you guys have a idea?

**Comment by ghost** [comment]
Sorry this wasn't the whole message, this is it: 
"Resource not found: The following package was not found in <arg default="$(find leo_description)/urdf/leo_sim.urdf.xacro" name="model"/>: leo_description"

**Comment by bjsowa** [comment]
Did you install the dependencies? You can use [rosdep](http://wiki.ros.org/rosdep) to do this.

Btw. I don't know if you realized, but you can install these packages from ROS repository.

**Comment by bjsowa** [comment]
I'm closing this issue due to lack of response
