### ISSUE TITLE
Depth camera issue in simulation

### ISSUE THREAD

**Issue by tlevendovics** [LeoRover/leo_simulator#4]
Hi, I'm using the gazebo simulation of the Leo rover. I wonder if depth is available from the camera? When I try to subscribe to the topic /camera/image_raw/compressedDepth with type sensor_msgs/CompressedImage I get the following error:

Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: rgb8).

I'm on ununtu 20.04 with noetic. The simulator is launched by roslaunch leo_gazebo leo_marsyard.launch.

Thanks in advance!

**Comment by bjsowa** [comment]
The camera does not produce Depth images. The reason you see this topic is that you have the [image_transport_plugins](http://wiki.ros.org/image_transport_plugins) installed which spawn these additional topics. The compressedDepth transport won't work for non-depth images.

**Comment by tlevendovics** [comment]
I see, thank you for the rapid reply!
