### ISSUE TITLE
marsyard terrain texture does not appear to load properly

### ISSUE THREAD

**Issue by woudie** [LeoRover/leo_simulator#9]
Hi,

I was trying to look at using the marsyard2021 world for a project I am involved in, but I am having trouble getting the terrain to load properly. Everything seems to build fine, so all the deps are there, but when I launch marsyard2021 it results in the followings:
![Screenshot from 2022-07-05 20-52-07](https://user-images.githubusercontent.com/8084590/177440856-7d946dca-46af-4e00-9e4e-e6e5f7078762.png)

I am not too sure what the issue is, I've checked that the terrain is included in the world file - but it looks fine there. Any idea what might be causing this?

**Comment by bjsowa** [comment]
Did you get any errors? 

You can try clearing the Gazebo heightmap cache files which often cause some weird bugs:
```
rm -rf ~/.gazebo/pagin
```

You can also try prebuild binaries from ROS distribution:
```
sudo apt install ros-noetic-leo-simulator
```

**Comment by woudie** [comment]
I did not get errors, but it looks like it was the heightmap cache files lol. Thanks for the help!
